version: "3.9"
services:
  # USERS POSTGRES
  users-db:
    image: postgres:15
    container_name: users-db
    environment:
      POSTGRES_DB: books-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elpi
    ports:
      - "5433:5432"
    networks:
      - spring-net

  # COMMUNITY POSTGRES
  community-db:
    image: postgres:15
    container_name: community-db
    environment:
      POSTGRES_DB: books-community
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elpi
    ports:
      - "5434:5432"
    networks:
      - spring-net

  # BOOKS POSTGRES
  books-db:
    image: postgres:15
    container_name: books-db
    environment:
      POSTGRES_DB: books-books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elpi
    ports:
      - "5435:5432"
    networks:
      - spring-net

  # USERS SERVICE
  users-service:
    build: ./users
    depends_on:
      - users-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/books-users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: elpi
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - spring-net

  # BOOKS-COMMUNITY SERVICE
  community-service:
    build: ./community
    depends_on:
      - community-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://community-db:5432/books-community
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: elpi
      USERS_SERVICE_URL: http://users-service:8082/users/exists/
      BOOKS_SERVICE_URL: http://books-service:8080/books/exists/
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - spring-net

  # BOOKS SERVICE
  books-service:
    build: ./books
    depends_on:
      - books-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://books-db:5432/books-books
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: elpi
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
